---

- name: Ensure that ProxySQL is running
  service:
    enabled: "{{ proxysql_service_enabled_state | default('yes') }}"
    name: proxysql
    state: "{{ proxysql_service_state | default('started') }}"

- name: Wait for the ProxySQL admin interface
  wait_for:
    connect_timeout: 2
    port: "{{ (proxysql_global_variables_kv['admin-mysql_ifaces'] | default('0.0.0.0:6032')).split(':')[1] }}"
    timeout: 60
  when: proxysql_service_enabled

- include_tasks: config/proxysql_backend_servers.yml
  when: proxysql_backend_servers

- include_tasks: config/proxysql_global_variables.yml
  when: >
        proxysql_global_variables and
        proxysql_global_variables_kv

- include_tasks: config/proxysql_mysql_users.yml
  when: proxysql_mysql_users

- include_tasks: config/proxysql_proxysql_servers.yml
  when: proxysql_proxysql_servers

- include_tasks: config/proxysql_query_rules.yml
  when: proxysql_query_rules

- include_tasks: config/proxysql_replication_hostgroups.yml
  when: proxysql_replication_hostgroups
