---

- name: Gather general variables
  include_vars: main.yml

- name: Gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: Check used repository
  fail:
    msg: Can't use the ProxySQL and Percona repository at the same time.
  when: proxysql_use_official_repo and proxysql_use_percona_repo

- include_tasks: facts.yml

- include_tasks: dependencies.yml

- include_tasks: proxysql-official-repo.yml
  when: proxysql_use_official_repo

- include_tasks: proxysql-percona-repo.yml
  when: proxysql_use_percona_repo

- include_tasks: preinst.yml

- include_tasks: install.yml

- include_tasks: config.yml
